[package]
name = "liquid_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
libgsh = { workspace = true, features = ["server"] }
glam = "0.29.2"
log = "0.4.27"
env_logger = "0.11.8"
rayon = "1.10.0"
ndarray = "0.16.1"
